-------------------------------------------------------------------------------
-- Author       name
-- Created      date
-- Project
-- Purpose      description of the business/technical purpose
--              using multiple lines as needed
-- Input        - tables used, 
                - main collection of fields used
                - main transformation
-- Output       - table FQDN
                - main output
-- 
-- Steps        - high-level steps and main transformations
-------------------------------------------------------------------------------
