select
        DISTINCT MSP_NAME,
        C.CLNT_MEMBERID,
        MSP_CODE,
        MSP_REGION,
        MSP_CW_PARTNERTYPE,
        MSP_PARTNERTYPE,
        date_trunc('MONTH',MSP_EFF_FROM_DTIMEUTC) as MSP_EFF_FROM_DTIMEUTC,
        CLNT_CODE,
        C.CLNT_SITEID,
        date_trunc('MONTH',C.CLNT_CREATION_DTIMEUTC) as  CLNT_CREATION_DTIMEUTC,
        EP.EP_REGID,
        EP.EP_NOCACCESSLEVEL,
        date_trunc('MONTH',EP.EP_REG_DTIMEUTC) as EP_REG_DTIMEUTC,

        C.CLNT_NOC_ACCESSLEVEL aS Site_NOC_ACCESS_LEVEL,
        SRVR_SP.SP_Alias as ServerServicePlan,
        EP_REG_TYPE_DEVICE,
        fd.ID as SF_COMPANY_ID,
        fd.CWS_IT_SUPPORT_PORTAL_ID_C
    FROM
        CW_DP_ANALYTICS.PRD.client_dim C
        LEFT JOIN CW_DP_ANALYTICS.PRD.msp_dim M on C.CLNT_MEMBERID = M.MSP_MEMBERID
        AND MSP_ACTIVERECORD = 1
        left join ANALYTICS.DBO_TRANSFORMATION.BASE_SALESFORCE__ACCOUNT fd on M.MSP_SF_ACC_ID = fd.CWS_ACCOUNT_UNIQUE_IDENTIFIER_C
        LEFT JOIN CW_DP_ANALYTICS.PRD.ENDPOINT_DIM EP ON EP.EP_SITEID = C.CLNT_SITEID
--         and ep.EP_REG_DTIMEUTC >= fd.CWS_TRIAL_START_DATE_C
--         and ep.EP_REG_DTIMEUTC <= fd.CWS_TRIAL_ACTUAL_COMPLETION_DATE_C --         and EP_ACT_STATUS = 'Active'
        --         and EP_ACTIVERECORD = 1
        LEFT JOIN CW_DP_ANALYTICS.PRD.SERVICEPLAN_DIM DSKTOP_SP ON (c.SP_Key_Desktop = DSKTOP_SP.SP_KEY)
        and DSKTOP_SP.SP_ACTIVERECORD = 1 --         and DSKTOP_SP.SP_EFF_FROM_DTIMEUTC >= fd.CWS_TRIAL_START_DATE_C
        --         and DSKTOP_SP.SP_EFF_FROM_DTIMEUTC <= fd.CWS_TRIAL_START_DATE_C
        LEFT JOIN CW_DP_ANALYTICS.PRD.SERVICEPLAN_DIM SRVR_SP ON (c.SP_Key_Server = SRVR_SP.SP_KEY)
        and SRVR_SP.SP_ACTIVERECORD = 1 --         and SRVR_SP.SP_EFF_FROM_DTIMEUTC >= fd.CWS_TRIAL_START_DATE_C
        --         and SRVR_SP.SP_EFF_FROM_DTIMEUTC <= fd.CWS_TRIAL_START_DATE_C
    WHERE
        CLNT_ACTIVERECORD = 1 --         AND CLNT_ACT_STATUS in ('1', 'true')